################### English navigation ####################

[[main]]
name = "Lab Overview"
url = "overview/"
weight = 1

[[main]]
name = "Research"
url = "research/"
weight = 2

[[main]]
name = "Members"
url = "members/"
weight = 3

[[main]]
name = "Publications"
url = "publications/"
weight = 4

[[main]]
name = "Notice"
url = "notice/"
weight = 5

[[main]]
name = "Join Us"
url = "join/"
weight = 6

[[main]]
name = "Access"
url = "https://www.naruto-u.ac.jp/access.html"
weight = 7

[[main]]
name = "Contact"
url = "https://forms.gle/27n7coB55JCUKAwFA"
weight = 8

# footer menu
[[footer]]
name = "Lab Overview"
url = "overview/"

[[footer]]
name = "Research"
url = "research/"

[[footer]]
name = "Members"
url = "members/"

[[footer]]
name = "Publications"
url = "publications/"

[[footer]]
name = "Contact"
url = "https://forms.gle/27n7coB55JCUKAwFA"
