################### Japanese navigation ####################

[[main]]
name = "研究室概要"
url = "overview/"
weight = 1

[[main]]
name = "メンバー"
url = "members/"
weight = 2

[[main]]
name = "業績"
url = "publications/"
weight = 3

[[main]]
name = "輪読会"
url = "reading/"
weight = 4

[[main]]
name = "お知らせ"
url = "notice/"
weight = 5

[[main]]
name = "一緒に研究したい方へ"
url = "join/"
weight = 6

[[main]]
name = "アクセス"
url = "https://www.naruto-u.ac.jp/access.html"
weight = 7

[[main]]
name = "お問い合わせ"
url = "https://forms.gle/27n7coB55JCUKAwFA"
weight = 8

# footer menu
[[footer]]
name = "研究室概要"
url = "overview/"

[[footer]]
name = "メンバー"
url = "members/"

[[footer]]
name = "業績"
url = "publications/"

[[footer]]
name = "輪読会"
url = "reading/"

[[footer]]
name = "お問い合わせ"
url = "https://forms.gle/27n7coB55JCUKAwFA"
